- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
    include_vars: "{{ lookup('first_found', possible_files) }}"
    vars:
      possible_files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - default.yaml
  - name: Install containerd separately (CentOS 8).
    package:
      name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      state: present
    when: ansible_distribution_major_version | int == 8
  - name: install epel and dnf plugins
    package:
      name: 
        - epel-release
        - dnf-plugins-core
  - name: add docker repository 
    command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - name: install common applications
    package:
      name:
        - htop
        - docker-ce
  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: started
      enabled: yes
