- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install epel
    dnf:
      name: 
        - epel-release
  - name: install common applications
    dnf:
      name:
        - htop
        - docker-ce
        